version: 2.1
orbs:
  cypress: cypress-io/cypress@1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  check_install:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo Hello, World!
workflows:
  my-custom-workflow:
    jobs:
      - check_install
      - cypress/run:
          command: npx cypress run-ct --record --key 10d8a471-d7f2-4701-afd5-691ec248d7bb
